name: Build & Test CI

on:
  push:
    branches:
      - dev-ts
  pull_request:
    branches:
      - dev-ts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: yarn-cache
        name: Get Yarn cache path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/checkout@722adc6

      - uses: actions/setup-node@1c5c137
        with:
          node-version: 12.x

      - uses: actions/cache@70655ec
        name: Load Yarn cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile && yarn bootstrap
        name: Install dependencies

      - run: yarn build
        name: Build all packages

      - run: yarn test
        name: Run all tests
